### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by FYI-PSA** [zbarnz/Google_AI_Overviews_Blocker#1]
Hello! This is an amazing extension, are there any plans to port it for Firefox use too? Thanks

**Comment by zbarnz** [comment]
> Hello! This is an amazing extension, are there any plans to port it for Firefox use too? Thanks

There is not currently a firefox version. It should be fairly easy to port over. Firefox uses Manifest V2 and there will be a few API differences.

**Comment by trlkly** [comment]
@zbarnz Firefox can use Manifest V3. It just doesn't allow service workers. But you aren't using any, so that should be fine. You'd just need to add a couple Firefox-specific keys to the manifest.json file.

I can make a Pull Request if you'd like, and add the small changes. But then it would be good if you would upload the extension to https://addons.mozilla.org, so that Mozilla will sign the addon.

**Comment by zbarnz** [comment]
Here is a link to the firefox version: https://addons.mozilla.org/en-US/firefox/addon/hide-google-ai-overviews/
